### ISSUE TITLE
Cannot edit/save any offers

### ISSUE THREAD

**Issue by kmay90** [newhere-team/nh-website#12]
works locally and with test; not live because a column for the facebook url is missing.
changing database schemes live is new to me and although live resembles a development environment I'd like to update the database schemes as if the website and cms was used by cms-user. If this approach doesn't seem worth the time considering time-pressure I won't and cause downtime on the server.

looks like there exists a [migration.php](https://github.com/newhere-team/nh-website/blob/master/database/migrations/2017_01_24_143640_add_facebook_field_to_offers.php) for it

**Comment by ScrambledRK** [comment]
```
undefined column: 7 FEHLER:  Spalte »facebook_url« von Relation »nh_offers« existiert nicht\nLINE 1: insert into \"nh_offers\" (\"website\", \"facebook_url\", \"email\",...\n                                   
```
who would have thought, ... seems related to the missing facebook_url after all ...

**Comment by ScrambledRK** [comment]
https://laravel.com/docs/5.4/migrations

**Comment by ScrambledRK** [comment]
Backed up the database, executed the migration on live. Offers can be updated now and facebook links set.

**Comment by ScrambledRK** [comment]
see [ground-up branch](https://github.com/newhere-team/nh-website/tree/ground-up)
