### ISSUE TITLE
rename "Als NGO Registrieren" -> "Als 'service-provider' registrieren"

### ISSUE THREAD

**Issue by kmay90** [newhere-team/nh-website#13]
Side menu front page

**Comment by ScrambledRK** [comment]
menu entries and other internal translations are not part of the accessible cms

**Comment by ScrambledRK** [comment]
related to #14

**Comment by ScrambledRK** [comment]
see [ground-up branch](https://github.com/newhere-team/nh-website/tree/ground-up)
