### ISSUE TITLE
improve the "profile-change-request" user experience 

### ISSUE THREAD

**Issue by ScrambledRK** [newhere-team/nh-website#43]
once the user has registered and activated the account (#41,#42), logged in and lands on the dashboard; it is unclear what the user is now supposed to do. to make it easier for the user change the following: 

* immediately force new users to choose their desired role/provider (profile-change-request)
* explain the process a little bit better ...
  * "search here for a provider you want to join"
  * "and administrator will process your request shortly, you will get a mail soon" (see #41)
  * "if you have any questions contact "info at" ... 
* ensure all texts are translated to both english and german (including error messages, see #14)

the most common choice will either be to join an existing provider or to create one. In case the user wants to create a new provider explain / make clear through the form:
* that all the given data will be public (once the provider is enabled)
* describe what each field means (e.g. "title" is the name it will be listed under; etc.)

**Comment by ScrambledRK** [comment]
![provider_form](https://user-images.githubusercontent.com/1149332/36212817-4308265c-11a5-11e8-9fd9-3ab54b842611.jpg)

I could use some feedback regarding the address / logo upload ... 
I'll upload the changes soon to test ...

**Comment by kmay90** [comment]
Feedback:

1. Change text 'Logo oder Bild hochladen' to 'Logo hochladen' - we can then use this logo as the icon on the 'all providers' page (let's not worry about making them blue for the moment.

2. Change text 'ohne Adresse (nur webseite)' to 'Anbieter ohne Adresse (nur Webseite)' just to clarify

**Comment by ScrambledRK** [comment]
alright can do - was hoping to get away with 'ohne Adresse (nur Webseite)' - same with image/logo because those 2 components are shared between offers and providers. I'll change it though.

**Comment by ScrambledRK** [comment]
k, closed then - and new issues shall be created in case anything comes up
