### ISSUE TITLE
Languages are mixed

### ISSUE THREAD

**Issue by DasPosch** [newhere-team/nh-website#61]
when using the English version and asking for a profile change, the set-up is showing in mixed languages ('cancel' - 'weiter') 

![bildschirmfoto 2018-03-12 um 10 32 37](https://user-images.githubusercontent.com/37066720/37276401-ddd908b8-25e1-11e8-83a4-58282d71cff4.png)

**Comment by ScrambledRK** [comment]
fixed on test.newhere.org
