### ISSUE TITLE
welcomeoida should redirect to www.newhere.org

### ISSUE THREAD

**Issue by ScrambledRK** [newhere-team/nh-website#7]
> welcomeoida should redirect to www.newhere.org

[160](https://github.com/magnolo/newhere/issues/160): @manifroh on Jan 27 • edited by kmay90

**Comment by ScrambledRK** [comment]
should it be like the *.at to *.org redirect? automatic and permanent or should it still show the old website and redirect after a while? is welcomeoida still of use?

**Comment by kmay90** [comment]
Redirect to www.newhere.org is fine

**Comment by ScrambledRK** [comment]
- [x] redirect welcomeoida.at
- [x] redirect www.welcomeoida.at
